name: crear y notificar

on:
  push:
    branches:
      - guamarmor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Give execution permission to Gradle wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Send email notification
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: " Ejecución correcta del flujo"
        to: ${{ secrets.PROFESORA_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          La ejecución del flujo en la rama suuvus ha sido correcta.
